export const projects = [
  {
    num: "01",
    category: "FullStack",
    title: "Bummer",
    description:
      "E-commerce website, Payment gateway and user-friendly shopping experience.",
    stack: [
      { name: "Javascript" },
      { name: "ReactJs" },
      { name: "Strapi" },
      { name: "TailwindCss" },
    ],
    image: "/assets/work/e-com.png",
    live: "https://bummer-tusharupadhyay.vercel.app/",
    github: "https://github.com/tushar-upadhya/e-com-full",
  },
  {
    num: "02",
    category: "Frontend",
    title: "PRM",
    description:
      "Customizable sections for users to define their preferred tech stacks, social links, databases, frameworks libraries, and programming languages.",
    stack: [
      { name: "Javascript" },
      { name: "ReactJS" },
      { name: "Strapi" },
      { name: "TailwindCss" },
      { name: "React-Router-Dom" },
      { name: "ShadcnUi" },
    ],
    image: "/assets/work/readme.png",
    live: "https://prm-tusharupadhyay.vercel.app/",
    github: "https://github.com/tushar-upadhya/Profile-Read-Maker",
  },
  {
    num: "03",
    category: "Frontend",
    title: "code2img",
    description:
      "A web app, allowing tech creators to showcase their code in a visually appealing format.",
    stack: [
      { name: "Javascript" },
      { name: "TypeScript" },
      { name: "NextJS" },
      { name: "Html2canvas" },
      { name: "Strapi" },
      { name: "TailwindCss" },
    ],
    image: "/assets/work/codeToImage.png",
    live: "https://code2img-tusharupadhyay.vercel.app/",
    github: "https://github.com/tushar-upadhya/code2img",
  },
  {
    num: "04",
    category: "Frontend",
    title: "WriterPro",
    description:
      "You can see letter count, word count, line count, and text memory size in Statistics section. You can also set text size according to your requirement and of your choice.",
    stack: [
      { name: "Javascript" },
      { name: "NextJS" },
      { name: "Axios" },
      { name: "TailwindCss" },
    ],
    image: "/assets/work/laptop.png",
    live: "https://writerpro-tushar-upadhyay.vercel.app/",
    github: "https://github.com/tushar-upadhya/writer-pro",
  },
  {
    num: "05",
    category: "Frontend",
    title: "Bhagavad Gita",
    description: "Most Powerful text book with model UI.",
    stack: [
      { name: "Javascript" },
      { name: "NextJS" },
      { name: "Axios" },
      { name: "TailwindCss" },
      { name: "Framer-Motion" },
      { name: "React-Query" },
      { name: "ShadcnUi" },
    ],
    image: "/assets/work/gita.png",
    live: "https://bhagavad-gita-tusharupadhyay.vercel.app/",
    github: "https://github.com/tushar-upadhya/Bhagavad-Gita",
  },
  {
    num: "07",
    category: "Frontend",
    title: "Chat 2 Chat",
    description:
      "It's built with end-to-end encryption technology and designed to be responsive on all devices.",
    stack: [
      { name: "Javascript" },
      { name: "NextJS" },
      { name: "firebase" },
      { name: "DaisyUi" },
      { name: "TailwindCss" },
    ],
    image: "/assets/work/chat.png",
    live: "https://chat-tusharupadhyay.vercel.app/",
    github: "https://github.com/tushar-upadhya/chatt",
  },
  {
    num: "08",
    category: "Frontend",
    title: "Logic Board",
    description:
      "Allows users to import images from their local desktop, switch to a dark mode for a comfortable viewing experience, and save their canvas as an image.",
    stack: [
      { name: "TypeScript" },
      { name: "NextJS" },
      { name: "UUID" },
      { name: "TailwindCss" },
      { name: "ShadcnUi" },
    ],
    image: "/assets/work/logic.png",
    live: "https://excalidraw-tusharupadhyay.vercel.app/",
    github: "https://github.com/tushar-upadhya/excalidraw",
  },
  {
    num: "09",
    category: "Full Stack",
    title: "Hotel",
    description: "Experience hospitality at its finest.",
    stack: [
      { name: "TypeScript" },
      { name: "NextJS" },
      { name: "TailwindCSS" },
      { name: "ShadcnUi" },
      { name: "Strapi" },
    ],
    image: "/assets/work/hotel.png",
    live: "https://github.com/tushar-upadhya/hotel",
    github: "https://github.com/tushar-upadhya/hotel",
  },
];
